### ISSUE TITLE
Any plan for SpinalHDL + Verilator++ ?

### ISSUE THREAD

**Issue by zhuhz22** [abmfy/abmfy.github.io#2]
Hi @abmfy ，
Thank you for your excellent ***Weekly9::造台计算机，但是 SpinalHDL + Verilator***! However, it seems that there'll be sequels, which include state machines, SRAM and UART. Just wondering that is there any plan for sequels? It will be wonderful if the answer is “Yes” for many teams of the course *Computer Composition Principles*!
![image](https://github.com/user-attachments/assets/3d857588-beb1-4644-92c3-522d97a541da)

**Comment by abmfy** [comment]
Scheduled!
